cmake_minimum_required(VERSION 3.28)
project(王道408数据结构代码题)

set(CMAKE_CXX_STANDARD 14)

add_executable(p20_01 线性表/p20_01.cpp)
add_executable(p20_02 线性表/p20_02.cpp)
add_executable(p20_03 线性表/p20_03.cpp)
add_executable(p20_04 线性表/p20_04.cpp)
add_executable(p20_05 线性表/p20_05.cpp)
add_executable(p20_06 线性表/p20_06.cpp)
add_executable(p20_07 线性表/p20_07.cpp)